# Generated by Django 2.2.28 on 2022-10-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressrymrfcjwdj'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressrymrfcjwdj',
            name='asdfgh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
