# Generated by Django 2.2.28 on 2022-10-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_addressrymrfcjwdj_asdfgh'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressrymrfcjwdj',
            name='qwert',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
