# Generated by Django 2.2.28 on 2022-10-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_addressrymrfcjwdj_qwert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qqerty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdfghj', models.BigIntegerField()),
            ],
        ),
    ]
